### ISSUE TITLE
hitting 2 birds with one stone: combined Unit & load- testing module

### ISSUE THREAD

**Issue by herrlutz** [NAVPERF/NAVLoadTest#12]
Dear developers,

first thing to mention, this project is really a great help for all performance- critical NAV installations! Thanks to all guys contributing to it!

Some thoughts to the overall testing...

1. i was thinking whether it would be an idea to combine unit- test tools and load test- tools within one application framework. When a company decides to integrate as well unit test automation ("Application Test Toolset for Microsoft Dynamics NAV 2013") as well as load test automation, there is a redundancy in development of the execution- skripting. For example, you have to develop the skripting of a customer specific process once in unit testing suite, and once in load- testing module. Wouldn´t it be a vision to have one application that handles both?

2. it would mean less investment for load test management when the overall skripting would be possible in C\AL instead of .NET language. Most NAV customer have good C\AL knowledge, but less knowledge in .NET. This is why some customers still use the old "Microsoft Business Solutions- Navision Benchmark Tool 1.00"

**Comment by wortho** [comment]
Hi,
Thanks for providing feedback about the framework. I can't comment on what plans MS have for the Application Test Toolset but I have my own opinions about the combining of  load testing and unit testing tools.
It is important to understand that there are important differences in the goals and the design of the NAV Load Test Scenarios and the Application Test Toolset Tests.
1. Scope: 
The Application Test Toolset tests are designed to test the functionality of individual C/AL objects and methods in isolation. These are executed in the NAV Server only so there is no client-server communication involved.
The NAV Load Test Scenarios test end-to-end user interactions with a client. They client service is hosted in IIS, so the tests measure the resources consumed by the client layer, the NAV Server, SQL Server and the communications between those layers. 
2. Data Isolation: 
Application Test Toolset tests should be designed to be data-independent and to be isolated from other tests. Any changes done to the database through running of tests from the Test Tool are automatically rolled back using the Test Isolation feature.
The NAV Load Test Scenarios are dependent on existing data and also create persistent data and are also dependent on the data created by other tests. One of the goals of the Load Tests Scenarios is to observe how the scenario performance is impacted as the dataset grows. One of the hardest parts of writing load test scenarios is ensuring that they continue to run predictably as the dataset changes.

While it is possible to run multiple iterations of the Application Test Toolset tests to get statistical information about the performance of specific C/AL methods it is not the same as running the NAV Load Test Scenarios.

Regarding Navision Benchmark Tool. The C/AL objects in the Navision Benchmark Tool can still be used in later versions of NAV. However these tests are only testing the NAV Server and SQL Server layers and do not involve any client interactions. 

Your request for creating a new C/AL testing framework is not an issue with this toolkit. It is a request for a new NAV feature so it should be sent to the NAV team via the normal Partner feedback channels. 

I am closing the issue for that reason.

Regards,

David

**Comment by garglalit** [comment]
please tell me how should i proceed as i have to load test the Nav 2013 windows client application.
What tool should i use and what is the procedure to load test a NAV windows client Application
