### ISSUE TITLE
NAV2013R2 branch unable to use internationalized captions

### ISSUE THREAD

**Issue by tfenster** [NAVPERF/NAVLoadTest#14]
Hello,

I am trying to use the NAV2013R2 branch on an internationalized solution (mainly german). I am setting de-DE as value for "Service Language" in the NAV Server instance as well as for "Language" in web.conf for the Web Client. Still I only get english captions and don't find a way to configure any locale for the client. Is there any way to make the 2013R2 client return captions for a specific language?

Regards,
Tobias

**Comment by wortho** [comment]
I haven't yet found a way to select the language for Client Service. In NAV2016 the web client uses the language settings of the users profile (Danish) but the Client Service still uses the default language (English).
Maybe Freddy can help with this one.

PS. I am interested to know. When you are doing performance testing; how does it matter what language the Client is using?

**Comment by freddydk** [comment]
In ClientSessionExtensions you will find this line:

var sessionParameters = new ClientSessionParameters {CultureId = CultureInfo.CurrentCulture.Name};

Changing the CultureId should do the trick.


/Freddy

**Comment by tfenster** [comment]
The following worked for me, very close to what you suggested
```
sessionParameters.UICultureId = CultureInfo.GetCultureInfoByIetfLanguageTag(uiCulture).Name;
```
Once again thanks a lot!

David, I've implemented it as an additional setting. Would you want to add it to your repo?

**Comment by wortho** [comment]
Yes. Send a pull request.

**Comment by tfenster** [comment]
tried to, I hope I got it right and you are only seeing the UICulture stuff and not my tests
