### ISSUE TITLE
Allow easier sorting and filtering

### ISSUE THREAD

**Issue by tfenster** [NAVPERF/NAVLoadTest#15]
Hello,

I need to do some sorting and filtering on a table in a subpage as we are currently looking into different ways to implement the table and want to find out what the performance impact for each is. As I couldn't find an easier way I am doing the following to store all columns and then do some sorting and filtering:

```c#
        private Dictionary<string, ClientRepeaterColumnControl> getExplorerColumns()
        {
            if (explorerColumns == null)
            {
                explorerColumns = new Dictionary<string, ClientRepeaterColumnControl>();

                foreach (ClientRepeaterColumnControl column in explorerPage.Repeater().Columns)
                {
                    if (!explorerColumns.ContainsKey(column.Caption))
                        explorerColumns.Add(column.Caption, column);
                }
            }

            return explorerColumns;
        }

        public void filter(string filterField, string filterValue, UserContext userContext)
        {
            var column = getExplorerColumns()[filterField];
            ClientLogicalForm filters = column.Action("Filter...").InvokeCatchDialog();
            TestScenario.SaveValueWithDelay(filters.Control(filterField), filterValue);
            filters.Action("OK").Invoke();
        }

        public void sortAscending(string sortField)
        {
            var column = getExplorerColumns()[sortField];
            column.Action("Ascending").Invoke();
        }

        public void sortDescending(string sortField)
        {
            var column = getExplorerColumns()[sortField];
            column.Action("Descending").Invoke();
        }
```
Is there an easier or better way to do this?

Regards,
Tobias

**Comment by wortho** [comment]
Hi Tobias,
Great suggestion. I added some examples using your suggestion here https://github.com/NAVPERF/NAVLoadTest/pull/17

The only difference is that I use the InvokeInteraction pattern to ensure that the client session waits for the interaction to complete.

Regards,

David

**Comment by tfenster** [comment]
Hi David,

thanks, once again worked perfectly. Probably a question that shows that I am not that familiar with git: How can I add this to my repo? It only shows that I am some commits ahead of your repo but I can't get your changes to mine. Can you kindly give me an indication where to stark looking?

Regards,
Tobias

**Comment by wortho** [comment]
Hi Tobias,

Here is the documentation explaining how to sync with a remote repo. 
https://help.github.com/articles/syncing-a-fork/

In your case the upstream repo is https://github.com/NAVPERF/NAVLoadTest.git

**Comment by tfenster** [comment]
I don't see the change. Is it possible that your pull request on the NAVPERF-Repo wasn't accepted yet or am I missing something else?

**Comment by wortho** [comment]
I have merged the changes to master now. You can also checkout a feature branch to see the changes before they are merged to master.
