### ISSUE TITLE
NAV2013R2 branch has problem resolving dependencies

### ISSUE THREAD

**Issue by tfenster** [NAVPERF/NAVLoadTest#16]
Hello,

if I try to just run the tests in NAV2013R2 branch I get the following error:
```
Unit Test Adapter threw exception: 
Could not load file or assembly 'Microsoft.Dynamics.Framework.UI.Client, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
Strong name validation failed. (Exception from HRESULT: 0x8013141A).
```
I could solve this by disabling strong name validation but I guess I am missing something here?

Regards,
Tobias

**Comment by freddydk** [comment]
You can take a signed copy of the DLL from the Test Assemblies folder in the root of the NAV 2013R DVD.

/Freddy

**Comment by tfenster** [comment]
Thanks, that works perfectly
