### ISSUE TITLE
Error reading JToken from JsonReader

### ISSUE THREAD

**Issue by ishevchenko** [NAVPERF/NAVLoadTest#21]
Hi,
When I run tests from master it fails with error "CommunicationException: Error reading JToken from JsonReader". Tried using windows and nav authenication. Is it a known issue or have I configured something wrong? 

Full exception:
Result StackTrace:	
в Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader)
   в Newtonsoft.Json.Linq.JToken.Parse(String json)
   в Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.<>c__DisplayClass2.<EndOpenSession>b__1()
   в Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.ConvertExceptions[T](Func`1 action)
 ---  ---
    в Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.ConvertExceptions[T](Func`1 action)
   в Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.EndOpenSession(IAsyncResult result)
   в Microsoft.Dynamics.Framework.UI.Client.ClientSession.<>c__DisplayClass4.<OpenSessionCallback>b__1()
   в Microsoft.Dynamics.Framework.UI.Client.ClientSession.HandleServiceExceptions(ClientSessionState errorState, Action action)
 ---  ---
    в Microsoft.Dynamics.Nav.UserSession.ClientSessionExtensions.AwaitReady(ClientSession clientSession, Action action, Func`2 readyCondition, Boolean allowClosed, Int32 maxDuration) в C:\GitSources\NAVLoadTest\Microsoft.Dynamics.Nav.UserSession\ClientSessionExtensions.cs:строка 322
   в Microsoft.Dynamics.Nav.UserSession.ClientSessionExtensions.AwaitReady(ClientSession clientSession, Action action) в C:\GitSources\NAVLoadTest\Microsoft.Dynamics.Nav.UserSession\ClientSessionExtensions.cs:строка 300
   в Microsoft.Dynamics.Nav.UserSession.ClientSessionExtensions.OpenSession(ClientSession clientSession, String uiCultureId) в C:\GitSources\NAVLoadTest\Microsoft.Dynamics.Nav.UserSession\ClientSessionExtensions.cs:строка 42
   в Microsoft.Dynamics.Nav.UserSession.UserContext.OpenSession(String uiCultureId) в C:\GitSources\NAVLoadTest\Microsoft.Dynamics.Nav.UserSession\UserContext.cs:строка 52
   в Microsoft.Dynamics.Nav.TestUtilities.UserContextManager.CreateSession(TestContext testContext) в C:\GitSources\NAVLoadTest\Microsoft.Dynamics.Nav.TestUtilities\UserContextManager.cs:строка 71
   в Microsoft.Dynamics.Nav.TestUtilities.UserContextManager.GetUserContext(TestContext testContext) в C:\GitSources\NAVLoadTest\Microsoft.Dynamics.Nav.TestUtilities\UserContextManager.cs:строка 100
   в Microsoft.Dynamics.Nav.TestUtilities.TestScenario.Run(UserContextManager manager, TestContext testContext, Action`1 action, String actionName) в C:\GitSources\NAVLoadTest\Microsoft.Dynamics.Nav.TestUtilities\TestScenario.cs:строка 23
   в Microsoft.Dynamics.Nav.LoadTest.SmallBusinessScenarios.CreateAndPostPurchaseInvoice() в C:\GitSources\NAVLoadTest\Microsoft.Dynamics.Nav.LoadTest\SmallBusinessScenarios.cs:строка 68
Result Message:	
Method validation Microsoft.Dynamics.Nav.LoadTest.SmallBusinessScenarios.CreateAndPostPurchaseInvoice exception: 
System.InvalidOperationException: Communication error was thrown:
System.ServiceModel.CommunicationException: Error reading JToken from JsonReader. Path '', line 0, position 0. ---> Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0.
   в Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader)
   в Newtonsoft.Json.Linq.JToken.Parse(String json)
   в Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.<>c__DisplayClass2.<EndOpenSession>b__1()
   в Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.ConvertExceptions[T](Func`1 action)
   ---  ---
   в Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.ConvertExceptions[T](Func`1 action)
   в Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.EndOpenSession(IAsyncResult result)
   в Microsoft.Dynamics.Framework.UI.Client.ClientSession.<>c__DisplayClass4.<OpenSessionCallback>b__1()
   в Microsoft.Dynamics.Framework.UI.Client.ClientSession.HandleServiceExceptions(ClientSessionState errorState, Action action) ---> System.ServiceModel.CommunicationException: Error reading JToken from JsonReader. Path '', line 0, position 0. ---> Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0..

**Comment by freddydk** [comment]
Sounds like you are using the wrong version of the NAVLoadTest to connect to your version of NAV.
Please check that you have the right versions of the Load Test DLL’s and the right version of the code from Github.

Thanks

/Freddy

**Comment by ishevchenko** [comment]
You are right, I've taken a missmatched version of code. Thanks.
