### ISSUE TITLE
Get Control by Caption finds wrong Control

### ISSUE THREAD

**Issue by matthiasbier** [NAVPERF/NAVLoadTest#27]
If two Controls have a caption with the same ending, the Control function might return the wrong one, depending on the column order in the client. For example "No." and "Job No." end the same way. If "Job No." is placed before "No." in the column list the Control("No.") function return the "Job No."-Control.

Is there a reason for comparing the caption ending only?

```c#
public static ClientLogicalControl Control(this ClientLogicalControl control, string controlCaption)
        {
            try
            {
                return control.ContainedControls.First(c => c.Caption.Replace("&", "").EndsWith(controlCaption));
            }
            catch (InvalidOperationException exception)
            {
                control.WriteControlCaptions<ClientLogicalControl>();
                throw new ArgumentOutOfRangeException(string.Format("Could not find a control with caption {0}",controlCaption), exception);
            }
        }
```

**Comment by wortho** [comment]
Hi Matthias,

No. I think it was intended to make it easier if there were spaces etc. in the caption. I have also had this problem of not finding the right controls. I have an example I can add to the repo.



Regards,

David

**Comment by matthiasbier** [comment]
Hi David,

Thanks for the confirmation.

In my case I added an optional parameter to the function that forces an
exact match.
I think it would be a good idea to add some kind of hint about this to the
repo...

Regards,

Matthias


David Worthington <notifications@github.com> schrieb am Do., 30. Aug. 2018,
07:03:

**Comment by wortho** [comment]
See this PR https://github.com/NAVPERF/NAVLoadTest/pull/28
