### ISSUE TITLE
Dialog were not find at Action

### ISSUE THREAD

**Issue by agartz** [NAVPERF/NAVLoadTest#29]
Hi,
If I want to register warehouse pick, then no dialogue is returned, no matter how I try it. If someone had a solution, because I have the same problem when posting warehouse receipts. The call always returns the value null for the dialog:

Var dialog = WarehousePickCard.Action("Register Pick").InvokeCatchDialog();

best regard,
annika

**Comment by wortho** [comment]
Hi Annika,

Usually it is because there is a validation error that blocks the action so that the expected dialog doesn't show. Try opening the created document created by the test and then clicking on the action to see if you get the same error.

Regards,

David

**Comment by wortho** [comment]
Closing as there is no reply after 1 month.
